#!/usr/bin/env node
// Generate the per-kit glue under kits.gen/ (gitignored). Next.js has no
// import.meta.glob, so discovery happens here at build time instead:
//
//   manifests.ts  — typed, sorted kit list (from each kit.json)
//   <slug>.css    — Tailwind v4 entry: imports the kit's globals.css
//                   UNTOUCHED and adds @source for the kit + _base .tsx
//                   sources (they live outside the demo root, so
//                   Tailwind's automatic detection never finds them)
//   <slug>.ts     — imports the kit CSS + the kit's section modules in
//                   BARREL ORDER (parsed from src/sections/index.ts —
//                   its line order is the canonical composition chain)
//   index.ts      — slug → dynamic import of <slug>.ts, so each kit's
//                   CSS+JS loads only on that kit's page
//
// Kit files are never edited — they must stay byte-identical to what
// ships in the published bundle. Runs from predev/prebuild.

import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const DEMO = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const KITS = resolve(DEMO, '../kits');
const OUT = resolve(DEMO, 'kits.gen');

const entries = await readdir(KITS, { withFileTypes: true });
const slugs = entries
  .filter((e) => e.isDirectory() && e.name !== '_base')
  .map((e) => e.name)
  .sort();

await rm(OUT, { recursive: true, force: true });
await mkdir(OUT, { recursive: true });

const manifests = [];
for (const slug of slugs) {
  const manifest = JSON.parse(await readFile(resolve(KITS, slug, 'kit.json'), 'utf8'));
  manifests.push({ slug, ...manifest });

  // `export * from './Hero';` lines, in file order.
  const barrel = await readFile(resolve(KITS, slug, 'src/sections/index.ts'), 'utf8');
  const files = [...barrel.matchAll(/export\s+\*\s+from\s+['"]\.\/([\w-]+)['"]/g)].map((m) => m[1]);

  await writeFile(
    resolve(OUT, `${slug}.css`),
    [
      '/* generated by scripts/gen-kits.mjs — do not edit */',
      `@import "../../kits/${slug}/src/globals.css";`,
      `@source "../../kits/${slug}/src";`,
      '@source "../../kits/_base/src";',
      '',
    ].join('\n'),
  );

  await writeFile(
    resolve(OUT, `${slug}.ts`),
    [
      '// generated by scripts/gen-kits.mjs — do not edit',
      `import './${slug}.css';`,
      "import type { SectionRef } from './types';",
      '',
      'export const sections: SectionRef[] = [',
      ...files.map(
        (f) =>
          `  { file: '${f}', load: async () => (await import('../../kits/${slug}/src/sections/${f}')) as Record<string, unknown> },`,
      ),
      '];',
      '',
    ].join('\n'),
  );
}

await writeFile(
  resolve(OUT, 'types.ts'),
  [
    '// generated by scripts/gen-kits.mjs — do not edit',
    'export interface SectionRef {',
    '  file: string;',
    '  load: () => Promise<Record<string, unknown>>;',
    '}',
    '',
    'export interface KitEntry {',
    '  sections: SectionRef[];',
    '}',
    '',
  ].join('\n'),
);

// Featured first, then by order, then by name.
manifests.sort(
  (a, b) =>
    Number(b.featured) - Number(a.featured) ||
    a.order - b.order ||
    a.name.localeCompare(b.name),
);

await writeFile(
  resolve(OUT, 'manifests.ts'),
  [
    '// generated by scripts/gen-kits.mjs — do not edit',
    'export interface Kit {',
    '  slug: string;',
    '  name: string;',
    '  description: string;',
    '  whenToUse: string;',
    '  tags: string[];',
    '  featured: boolean;',
    '  order: number;',
    '  accent?: string | null;',
    '  thumbnail?: string | null;',
    '}',
    '',
    `export const kits: Kit[] = ${JSON.stringify(manifests, null, 2)};`,
    '',
  ].join('\n'),
);

await writeFile(
  resolve(OUT, 'index.ts'),
  [
    '// generated by scripts/gen-kits.mjs — do not edit',
    "import type { KitEntry } from './types';",
    '',
    'export const kitModules: Record<string, () => Promise<KitEntry>> = {',
    ...slugs.map((s) => `  ${JSON.stringify(s)}: () => import('./${s}'),`),
    '};',
    '',
  ].join('\n'),
);

console.log(`gen-kits: ${slugs.length} kits → kits.gen/ (${slugs.join(', ')})`);
