// MCP server for the kits — lets an agent (Claude Code, Cursor, …)
// browse the kit catalog, pick one, and copy it into a project.
// Streamable HTTP at /api/mcp (stateless — no Redis needed).
//
// The data source is dist/kits-bundle.json, the published artifact
// every consumer uses (generated by scripts/pack-kits.mjs in prebuild).
// `merged(slug)` = { ...base, ...kit } — a copied kit is a complete,
// buildable UI library.

import { createMcpHandler } from 'mcp-handler';
import { z } from 'zod';
import bundle from '../../../../dist/kits-bundle.json';

interface KitTokens {
  base: Record<string, string>;
  dark?: Record<string, string>;
}

interface KitManifest {
  slug: string;
  name: string;
  description: string;
  whenToUse: string;
  tags: string[];
  featured: boolean;
  order: number;
  accent?: string | null;
  /** The kit's token declaration, derived from src/globals.css at pack time. */
  tokens?: KitTokens;
}

// The "corner things" every system has — the token subset worth surfacing
// at selection time (full set via get_kit). Plus every `font-*` the kit
// declares (main/secondary typefaces).
const ESSENTIAL_TOKEN_KEYS = ['primary', 'background', 'foreground', 'radius'];

function tokenEssentials(tokens: KitTokens | undefined): Record<string, string> {
  if (!tokens) return {};
  const out: Record<string, string> = {};
  for (const key of Object.keys(tokens.base)) {
    if (ESSENTIAL_TOKEN_KEYS.includes(key) || key.startsWith('font-')) {
      out[key] = tokens.base[key]!;
    }
  }
  return out;
}

const base = bundle.base as Record<string, string>;
const kits = bundle.kits as Record<
  string,
  { manifest: KitManifest; files: Record<string, string> }
>;

const REPO = 'vev-design/kopla-kits';
const SLUGS = Object.keys(kits).sort();

const decode = (b64: string) => Buffer.from(b64, 'base64').toString('utf8');

/** base ∪ kit — kit files win, per the workspace model in CONTRACT.md. */
const merged = (slug: string) => ({ ...base, ...kits[slug]!.files });

/** Section components in composition order, parsed from the kit's barrel. */
function sectionChain(slug: string): string[] {
  const barrel = decode(kits[slug]!.files['src/sections/index.ts'] ?? '');
  return [...barrel.matchAll(/export\s+\*\s+from\s+['"]\.\/([\w-]+)['"]/g)].map((m) => m[1]!);
}

function copyInstructions(slug: string, dir: string): string {
  return [
    `Copy the "${slug}" kit into ${dir}/ as a standalone UI library:`,
    '',
    `  npx degit ${REPO}/kits/_base ${dir}`,
    `  npx degit ${REPO}/kits/${slug} ${dir} --force   # overlay — kit files win on collisions`,
    `  rm ${dir}/kit.json                              # gallery metadata, not a workspace file`,
    `  cd ${dir} && bun install && bun run build`,
    '',
    'The build produces dist/library.js (ESM, every section re-exported; react',
    'external), dist/theme.css (compiled Tailwind theme), and design.json (the',
    'token + section API surface). Authoring rules live in AGENTS.md.',
    '',
    'No git available? Fetch every file via the read_kit_file tool instead —',
    'list_kit_files gives the full path list.',
  ].join('\n');
}

const handler = createMcpHandler(
  (server) => {
    server.tool(
      'list_kits',
      'List the available design-system kits: manifest (name, description, tags), `whenToUse` selection guidance (use cases, tone, and what each kit is NOT for — the primary signal for picking the right kit), each kit’s section chain in composition order, and `tokenEssentials` (primary color, scheme ground, radius, typefaces — the knobs every system has; full token declaration via get_kit). A kit is a complete, buildable React + Tailwind UI library (theme tokens + 1–8 section components on a shared substrate).',
      {},
      () => {
        const catalog = SLUGS.map((slug) => {
          const { tokens, ...manifest } = kits[slug]!.manifest;
          return {
            ...manifest,
            sections: sectionChain(slug),
            tokenEssentials: tokenEssentials(tokens),
          };
        });
        return { content: [{ type: 'text', text: JSON.stringify(catalog, null, 2) }] };
      },
    );

    server.tool(
      'get_kit',
      'Get one kit: manifest with its FULL token declaration ({ base, dark? } — every custom property the kit exposes for overriding), section chain, the kit’s README (design rationale), and step-by-step instructions for copying it into a project as a standalone UI library.',
      {
        slug: z.enum(SLUGS as [string, ...string[]]).describe('Kit slug, from list_kits'),
        dir: z
          .string()
          .regex(/^[\w./-]+$/)
          .default('design-system')
          .describe('Target directory name used in the copy instructions'),
      },
      ({ slug, dir }) => {
        const text = [
          JSON.stringify(
            { ...kits[slug]!.manifest, sections: sectionChain(slug) },
            null,
            2,
          ),
          '',
          '── README ──',
          decode(kits[slug]!.files['README.md'] ?? ''),
          '── How to copy ──',
          copyInstructions(slug, dir),
        ].join('\n');
        return { content: [{ type: 'text', text }] };
      },
    );

    server.tool(
      'list_kit_files',
      'List every file of the merged kit workspace (shared _base substrate + the kit’s overlay) with sizes — the exact tree a copy of the kit produces.',
      { slug: z.enum(SLUGS as [string, ...string[]]).describe('Kit slug, from list_kits') },
      ({ slug }) => {
        const files = merged(slug);
        const tree = Object.keys(files)
          .sort()
          .map((p) => `${p} (${Buffer.from(files[p]!, 'base64').length} bytes)`)
          .join('\n');
        return { content: [{ type: 'text', text: tree }] };
      },
    );

    server.tool(
      'read_kit_file',
      'Read one file from the merged kit workspace. Use with list_kit_files to copy a kit when direct repo access (degit/git) is unavailable.',
      {
        slug: z.enum(SLUGS as [string, ...string[]]).describe('Kit slug, from list_kits'),
        path: z.string().describe('Workspace-relative path, from list_kit_files'),
      },
      ({ slug, path }) => {
        const files = merged(slug);
        // hasOwn, not [path]: a prototype key ('__proto__', 'constructor')
        // must read as "no such file", not return Object.prototype.
        const file = Object.hasOwn(files, path) ? files[path] : undefined;
        if (file === undefined) {
          return {
            content: [{ type: 'text', text: `No file "${path}" in kit "${slug}" — see list_kit_files.` }],
            isError: true,
          };
        }
        return { content: [{ type: 'text', text: decode(file) }] };
      },
    );
  },
  {
    serverInfo: { name: 'kopla-kits', version: '0.1.0' },
  },
  { basePath: '/api' },
);

export { handler as GET, handler as POST, handler as DELETE };
