/** Static canvas cases: each geometry, missing values, long labels, and an empty state. */
export const ChartShowcase = [
  { label: 'Grouped bar', props: { title: 'Revenue by region', variant: 'bar', categories: ['Americas', 'Europe', 'Asia'], series: [{ name: 'Current', role: 'focus', values: [80, 65, 90] }, { name: 'Prior', role: 'context', values: [60, 55, 70] }], source: 'Illustrative data for this example.' } },
  { label: 'Stacked bar', props: { title: 'Portfolio mix', variant: 'stacked-bar', categories: ['2024', '2025'], series: [{ name: 'Core', role: 'focus', values: [40, 55] }, { name: 'Adjacent', role: 'positive', values: [30, 20] }, { name: 'New', role: 'context', values: [30, 25] }] } },
  { label: 'Line with missing observation', props: { title: 'Growth over time', variant: 'line', categories: ['2023', '2024', '2025', '2026'], series: [{ name: 'Current', role: 'focus', values: [45, null, 62, 80] }, { name: 'Prior', role: 'context', values: [40, 48, 60, 68] }] } },
  { label: 'Pie', props: { title: 'Response mix', variant: 'pie', categories: ['Agree', 'Neutral', 'Disagree'], series: [{ name: 'Responses', role: 'categorical', values: [60, 25, 15] }] } },
  { label: 'Donut', props: { title: 'Response share', variant: 'donut', background: 'muted', categories: ['Responses'], series: [{ name: 'Agree', role: 'focus', values: [75] }, { name: 'Other', role: 'context', values: [25] }] } },
  { label: 'Scatter', props: { title: 'Investment and growth', variant: 'scatter', xLabel: 'Investment', yLabel: 'Growth', series: [{ name: 'Portfolio', role: 'focus', values: [{ x: 10, y: 12 }, { x: 30, y: 28 }, { x: 50, y: 35 }, { x: 70, y: 62 }] }, { name: 'Comparison', role: 'context', values: [{ x: 20, y: 18 }, { x: 45, y: 25 }, { x: 60, y: 40 }] }] } },
  { label: 'Quantitative bubble', props: { title: 'Market opportunities', variant: 'bubble', xLabel: 'Market potential', yLabel: 'Growth', series: [{ name: 'Priority', role: 'focus', values: [{ x: 20, y: 25, size: 80 }, { x: 50, y: 65, size: 300 }, { x: 80, y: 40, size: 160 }] }, { name: 'Context', role: 'context', values: [{ x: 35, y: 40, size: 120 }, { x: 65, y: 30, size: 90 }] }] } },
  { label: 'Ten categories and long labels', props: { title: 'A comparison with a deliberately long finding that must wrap on a phone', variant: 'bar', categories: ['A deliberately long first category', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten'], series: [{ name: 'A deliberately long series name', values: [3, 4, -2, 8, 6, 4, 5, 7, 8, 10] }] } },
  { label: 'Empty', props: { title: 'No observations supplied', series: [] } },
];
